export const BUSINESS_LIST_REQUEST = 'BUSINESS_LIST_REQUEST';
export const BUSINESS_LIST_SUCCESS = 'BUSINESS_LIST_SUCCESS';
export const BUSINESS_LIST_FAIL = 'BUSINESS_LIST_FAIL';

export const BUSINESS_DETAILS_REQUEST = 'BUSINESS_DETAILS_REQUEST';
export const BUSINESS_DETAILS_SUCCESS = 'BUSINESS_DETAILS_SUCCESS';
export const BUSINESS_DETAILS_FAIL = 'BUSINESS_DETAILS_FAIL';

export const SEARCH_CRITERIA = 'SEARCH_CRITERIA';

export const BUSINESS_APPLY_REQUEST = 'BUSINESS_APPLY_REQUEST';
export const BUSINESS_APPLY_SUCCESS = 'BUSINESS_APPLY_SUCCESS';
export const BUSINESS_APPLY_FAIL = 'BUSINESS_APPLY_FAIL';