export const STUDENT_DETAILS_REQUEST = 'STUDENT_DETAILS_REQUEST';
export const STUDENT_DETAILS_SUCCESS = 'STUDENT_DETAILS_SUCCESS';
export const STUDENT_DETAILS_FAIL = 'STUDENT_DETAILS_FAIL';

export const STUDENT_APPLY_REQUEST = 'STUDENT_APPLY_REQUEST';
export const STUDENT_APPLY_SUCCESS = 'STUDENT_APPLY_SUCCESS';
export const STUDENT_APPLY_FAIL = 'STUDENT_APPLY_FAIL';
